version: '3.6'
services:
  influxdb:
    image: "influxdb:latest"
    ports: 
      - 8086:8086 
      - 8083:8083 
      - 2003:2003  
    container_name: "influxdb"
    restart: always
    volumes: 
      #- /usr/mabo/docker_server/conf/config.yml:/etc/docker/registry/config.yml
      - /usr/mabo/influxdb/influxdb_container:/var/lib/influxdb
      - /usr/mabo/influxdb/influxdb.conf:/var/lib/influxdb/influxdb.conf

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
       - "3000:3000"
#    env_file:
#      - 'env.grafana'
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - /usr/mabo/influxdb/grafana_container:/var/lib/grafana
      
       
        

