web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.example.com'
  ports:
    - '10080:80'
    - '10443:443'
    - '10022:22'
  volumes:
    - '/usr/zhy/gitlab/config:/etc/gitlab'
    - '/usr/zhy/gitlab/logs:/var/log/gitlab'
    - '/usr/zhy/gitlab/data:/var/opt/gitlab'
