{
 "title": "node monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ping & process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "aaa",
     "type": "blackmirror1-statusbygroup-panel",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "alias",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT pingg FROM \"test5\" WHERE \"eqpt_no\" = 'PEC0-04221' order by desc limit 5",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "aaa",
     "type": "blackmirror1-statusbygroup-panel",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "alias",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT pingg,dataa FROM \"test5\" WHERE \"eqpt_no\" = 'PEC0-04220' order by desc limit 1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "aaa",
     "type": "blackmirror1-statusbygroup-panel",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "0000000000000",
       "crit": "process error",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT pingg FROM \"test5\" WHERE \"eqpt_no\" = 'PEC0-04222' order by desc limit 1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "5E15发动机性能AVL台架ping",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "BEP_ASTZ",
       "query": "SELECT last(\"ping\") FROM \"test4\" WHERE \"eqpt_no\" = 'PEC0-04220' order by desc limit 5",
       "select": [
        [
         { "params": [ "status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "eqpt_no", "operator": "=", "value": "PEC0-00013" }
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "vonage-status-panel",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
     "targets": [
      {
       "displayType": "Regular",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "ping & process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "vonage-status-panel",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "alias",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT pingg FROM \"test5\" WHERE \"eqpt_no\" = 'PEC0-04221' order by desc limit 1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "h",
       "valueHandler": "String Threshold",
       "warn": "ping error"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "vonage-status-panel",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "alias",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT pingg FROM \"test5\" WHERE \"eqpt_no\" = 'PEC0-04220' order by desc limit 1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "h",
       "valueHandler": "String Threshold",
       "warn": "ping error"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "vonage-status-panel",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "alias",
       "crit": "process error",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT pingg FROM \"test5\" WHERE \"eqpt_no\" = 'PEC0-04222' order by desc limit 1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "h",
       "valueHandler": "String Threshold"
      }
     ]
    }
   ]
  },
  { "title": "data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "设备名称",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Data",
     "crit": "-",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT dataa FROM \"test5\" WHERE \"eqpt_no\" = 'PEC0-04223' order by desc limit 5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "h",
     "valueHandler": "String Threshold",
     "warn": "ok"
    }
   ]
  },
  {
   "title": "设备名称",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Data",
     "crit": "-",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT dataa FROM \"test5\" WHERE \"eqpt_no\" = 'PEC0-04224' order by desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "h",
     "valueHandler": "String Threshold",
     "warn": "ok"
    }
   ]
  },
  {
   "title": "设备名称",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "No data",
     "crit": 0.2,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT data FROM \"test4\" WHERE \"eqpt_no\" = 'PEC0-04220' order by desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "d",
     "valueHandler": "Number Threshold",
     "warn": 0.1
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "data",
     "crit": 3,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT data FROM \"test4\" WHERE \"eqpt_no\" = 'PEC0-04222' order by desc limit 5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "d",
     "valueHandler": "Number Threshold",
     "warn": 0.5
    }
   ]
  },
  { "title": "ping-process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "设备名称",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Status",
     "crit": "process crashed!",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT pingg FROM \"test5\" WHERE \"eqpt_no\" = 'PEC0-04221' order by desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "h",
     "valueHandler": "String Threshold",
     "warn": "ok"
    }
   ]
  },
  {
   "title": "设备名称",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Status",
     "crit": "process crashed!",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT pingg FROM \"test5\" WHERE \"eqpt_no\" = 'PEC0-04222' order by desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "h",
     "valueHandler": "String Threshold",
     "warn": "ok"
    }
   ]
  },
  {
   "title": "设备名称",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Status",
     "crit": "process crashed!",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT pingg FROM \"test5\" WHERE \"eqpt_no\" = 'PEC0-04220' order by desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "h",
     "valueHandler": "String Threshold",
     "warn": "ok"
    }
   ]
  },
  {
   "title": "设备名称",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 7 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "！",
     "crit": 0.01,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Critical Only",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ping FROM \"test4\" WHERE \"eqpt_no\" = 'PEC0-04225' order by desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "d",
     "valueHandler": "Number Threshold",
     "warn": -1
    }
   ]
  },
  {
   "title": "设备名称",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "ping或程序",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Critical Only",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ping FROM \"test4\" WHERE \"eqpt_no\" = 'PEC0-04224' order by desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "d",
     "valueHandler": "Number Threshold",
     "warn": -1
    }
   ]
  }
 ]
}