version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  secret: asecretforlocaldevelopment
  ntp: tcp
  headers:
    X-Content-Type-Options: [nosniff]
  host: https://mabo_docker_registry.org:5000
  relativeurls: false
  debug:
    addr: :5001
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

